# Versi API untuk object Secret
apiVersion: v1
# Jenis object: Secret untuk menyimpan data rahasia
kind: Secret
metadata:
  # Nama Secret yang direferensikan oleh StatefulSet dan Deployment backend
  name: mongo-secret
# Tipe Secret generik berisi pasangan key-value
type: Opaque
data:
  # Username root MongoDB ("admin") dalam format base64
  MONGO_ROOT_USERNAME: YWRtaW4=
  # Password root MongoDB ("supersecretpassword") dalam format base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
