# Versi API untuk object Deployment
apiVersion: apps/v1
# Deployment untuk aplikasi stateless order-service (menerima order lewat HTTP POST lalu mengirimnya ke queue RabbitMQ)
kind: Deployment
metadata:
  # Nama Deployment
  name: order-service
  # Namespace tempat Deployment dibuat
  namespace: ecommerce
  labels:
    # Label penanda aplikasi
    app: order-service
spec:
  # Jumlah pod
  replicas: 1
  # Pilih pod berdasarkan label app: order-service
  selector:
    matchLabels:
      app: order-service
  # Template pod
  template:
    metadata:
      labels:
        # Label pod; harus sama dengan selector
        app: order-service
        # Label versi, dipakai Istio untuk telemetry dan routing
        version: v1
    spec:
      containers:
        # Container order-service
        - name: order-service
          # Image dari GitHub Packages (bukan local image)
          image: ghcr.io/rizqiwidianto14/order-service:latest
          # Selalu tarik image dari registry, membuktikan image tidak berasal dari lokal
          imagePullPolicy: Always
          ports:
            # Port HTTP aplikasi
            - name: http
              containerPort: 3000
          env:
            # Port HTTP aplikasi (sama dengan nilai di .env)
            - name: PORT
              value: "3000"
            # Alamat RabbitMQ berdasarkan nama Kubernetes Service "rabbitmq" di namespace yang sama
            - name: AMQP_URL
              value: "amqp://rabbitmq:5672"
